name: Populate OKRs

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (optional)'
        required: false
        default: ''
  schedule:
    - cron: '0 8 * * *'  # daily at 00:00 UTC


jobs:
  populate-okr:
    runs-on: ubuntu-latest
    env:
      TECHFREN_GOOGLE_CLOUD_CRED: ${{ secrets.TECHFREN_GOOGLE_CLOUD_CRED }}
      TECHFREN_GA4_PROPERTY_ID: ${{ vars.TECHFREN_GA4_PROPERTY_ID }}
      TECHFREN_MONDAY_COM_API_TOKEN: ${{ secrets.TECHFREN_MONDAY_COM_API_TOKEN }}
      TECHFREN_MONDAY_COM_API_URL: ${{ vars.TECHFREN_MONDAY_COM_API_URL }}
      TECHFREN_MONDAY_COM_OKR_ITEMS_BOARD_ID: ${{ vars.TECHFREN_MONDAY_COM_OKR_ITEMS_BOARD_ID }}
      TECHFREN_MONDAY_COM_OKR_ITEMS_GROUP_ID: ${{ vars.TECHFREN_MONDAY_COM_OKR_ITEMS_GROUP_ID }}
      TECHFREN_MONDAY_COM_OKR_ITEMS_DATE_COLUMN_ID: ${{ vars.TECHFREN_MONDAY_COM_OKR_ITEMS_DATE_COLUMN_ID }}
      TECHFREN_MONDAY_COM_OKR_ITEMS_CURRENTVALUE_COLUMN_ID: ${{ vars.TECHFREN_MONDAY_COM_OKR_ITEMS_CURRENTVALUE_COLUMN_ID }}
      TECHFREN_MONDAY_COM_OKR_ITEMS_TARGETVALUE_COLUMN_ID: ${{ vars.TECHFREN_MONDAY_COM_OKR_ITEMS_TARGETVALUE_COLUMN_ID }}
      TECHFREN_MONDAY_COM_OKR_ITEMS_UPDATEKEY_COLUMN_ID: ${{ vars.TECHFREN_MONDAY_COM_OKR_ITEMS_UPDATEKEY_COLUMN_ID }}
      TECHFREN_MAILERLITE_API_TOKEN: ${{ secrets.TECHFREN_MAILERLITE_API_TOKEN }}
      WORKING_DIR: case_studies/TechFren

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        #with:
            #ref: main

      - name: Install Python dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run populate_okr script (only on main branch)
        working-directory: ${{ env.WORKING_DIR }}
        env:
          # Export values expected by the script
          TECHFREN_GOOGLE_CLOUD_CRED: ${{ env.TECHFREN_GOOGLE_CLOUD_CRED }}
          TECHFREN_GA4_PROPERTY_ID: ${{ env.TECHFREN_GA4_PROPERTY_ID }}
          TECHFREN_MONDAY_COM_API_TOKEN: ${{ env.TECHFREN_MONDAY_COM_API_TOKEN }}
          TECHFREN_MONDAY_COM_API_URL: ${{ env.TECHFREN_MONDAY_COM_API_URL }}
          TECHFREN_MONDAY_COM_OKR_ITEMS_BOARD_ID: ${{ env.TECHFREN_MONDAY_COM_OKR_ITEMS_BOARD_ID }}
          TECHFREN_MONDAY_COM_OKR_ITEMS_GROUP_ID: ${{ env.TECHFREN_MONDAY_COM_OKR_ITEMS_GROUP_ID }}
          TECHFREN_MONDAY_COM_OKR_ITEMS_DATE_COLUMN_ID: ${{ env.TECHFREN_MONDAY_COM_OKR_ITEMS_DATE_COLUMN_ID }}
          TECHFREN_MONDAY_COM_OKR_ITEMS_CURRENTVALUE_COLUMN_ID: ${{ env.TECHFREN_MONDAY_COM_OKR_ITEMS_CURRENTVALUE_COLUMN_ID }}
          TECHFREN_MONDAY_COM_OKR_ITEMS_TARGETVALUE_COLUMN_ID: ${{ env.TECHFREN_MONDAY_COM_OKR_ITEMS_TARGETVALUE_COLUMN_ID }}
          TECHFREN_MONDAY_COM_OKR_ITEMS_UPDATEKEY_COLUMN_ID: ${{ env.TECHFREN_MONDAY_COM_OKR_ITEMS_UPDATEKEY_COLUMN_ID }}
          TECHFREN_MAILERLITE_API_TOKEN: ${{ env.TECHFREN_MAILERLITE_API_TOKEN }}
        run: |
          python populate_okr.py